[package]
name = "llama2_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.9.4"
rand = "0.8.0"
rayon = "1.5.0"
tokenizers = "0.15.1"
byteorder = "1.4.3"
approx = "0.5.0"

